services:
  - type: web
    name: poc-dxc-parking
    env: node
    plan: free
    buildCommand: npm install --ignore-scripts --include=dev && npx vite build apps/web
    startCommand: node mock-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
